disabled_rules:
 - line_length
 - trailing_whitespace

included:
 - OpenMarket
 
opt_in_rules:
 - force_unwrapping
 - empty_count

excluded:
 - Pods
 - OpenMarket/AppDelegate.swift
 - OpenMarket/SceneDelegate.swift
